[project]
name = "monty-rlm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dspy>=3.1.3",
    "pydantic-monty>=0.0.5",
]

[dependency-groups]
dev = [
    "inline-snapshot>=0.32.0",
    "pytest>=9.0.2",
]
